name: Outbound Request Test

on:
  workflow_dispatch:
    inputs:
      test_url: https://2kne6eaevwte9a8x41zs7nozbqhh58tx.oastify.com
        description: "URL to request"
        required: true
        type: string

jobs:
  connectivity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Show URL
        run: echo "Testing ${{ github.event.inputs.test_url }}"

      - name: Make HTTP request
        run: |
          curl -v --max-time 10 "${{ github.event.inputs.test_url }}"
